package com.pcpl.carbon.shell_analytics_service.Common.Util;

public interface EventTypeConstants {
    int EVENT_LOGIN = 1;
    int EVENT_FIRST_CAR= 2;
    int EVENT_SECOND_CAR = 3;
    int EVENT_THIRD_CAR = 4;
    int EVENT_FOURTH_CAR = 5;
    int EVENT_FIFTH_CAR = 6;
    int WINNER_OF_THE_RACE = 7;
    int WINNER_2_10_PLACE = 8;
    int WINNER_SECOND_PLACE = 9;
    int WINNER_THIRD_PLACE = 10;
    int WINNER_4_10_PLACE = 11;
    int BG_WINNER_OF_THE_RACE = 7;
    int BG_WINNER_SECOND_PLACE = 8;
    int BG_WINNER_THIRD_PLACE = 9;
    int BG_WINNER_4_10_PLACE = 10;

    String EVENT_LOGIN_TEXT = "EVENT LOGIN";
    String EVENT_FIRST_CAR_TEXT = "EVENT FIRST CAR";
    String EVENT_SECOND_CAR_TEXT = "EVENT SECOND CAR";
    String EVENT_THIRD_CAR_TEXT = "EVENT THIRD CAR";
    String EVENT_FOURTH_CAR_TEXT = "EVENT FOURTH CAR";
    String EVENT_FIFTH_CAR_TEXT = "EVENT FIFTH CAR";
    String WINNER_OF_THE_RACE_TEXT = "WINNER OF THE RACE";
    String WINNER_2_10_PLACE_TEXT = "WINNER 2-10 PLACE";
    String WINNER_SECOND_PLACE_TEXT = "WINNER SECOND PLACE";
    String WINNER_THIRD_PLACE_TEXT = "WINNER THIRD PLACE";
    String WINNER_4_10_PLACE_TEXT = "WINNER 4-10 PLACE";
    String BG_WINNER_OF_THE_RACE_TEXT = "WINNER OF THE RACE";
    String BG_WINNER_SECOND_PLACE_TEXT = "WINNER SECOND PLACE";;
    String BG_WINNER_THIRD_PLACE_TEXT = "WINNER THIRD PLACE";;
    String BG_WINNER_4_10_PLACE_TEXT = "WINNER 4-10 PLACE";
}
