carbon.database.host = ${env.DB_HOST}
carbon.database.name = ${env.DB_NAME}
carbon.database.user = ${env.DB_USER}
carbon.database.port = ${env.DB_PORT}
carbon.database.pass = ${env.DB_PASSWORD}
#
#carbon.database.host = srl-events-do-user-8585301-0.f.db.ondigitalocean.com
#carbon.database.name = srl_events
#carbon.database.user = doadmin
#carbon.database.port = 25060
#carbon.database.pass = ${env.AIVEN_DB_PASSWORD}
